DROP TABLE IF EXISTS export.athena_b2b_emails;
CREATE TABLE export.athena_b2b_emails (
person_id BIGINT encode raw distkey,
    b2b_email varchar(1020) encode zstd,
    b2b_email_md5 char(32) encode raw,
    b2b_email_status varchar(1020) encode zstd,
    b2b_email_additional_status_info varchar(1020) encode zstd,
    b2b_domain_status varchar(1020) encode zstd,
    b2b_email_status_waterfall varchar(1020) encode zstd,
    b2b_email_vendor_status varchar(1020) encode zstd,
    b2b_email_query_type varchar(1020) encode zstd,
    b2b_email_domain_office_365 smallint encode raw
)
sortkey (person_id, b2b_email_md5)
;

INSERT INTO export.athena_b2b_emails
SELECT person_id,
    b2b_email,
    MD5(b2b_email) AS b2b_email_md5,
    b2b_email_status,
    b2b_email_additional_status_info,
    b2b_domain_status,
    b2b_email_status_waterfall,
    b2b_email_vendor_status,
    b2b_email_query_type,
    b2b_email_domain_office_365
FROM (
    SELECT production_business_emails.person_id,
        production_business_emails.email AS b2b_email,
        COALESCE(production_validated_emails.status,'Unverified') AS b2b_email_status,
        COALESCE(production_validated_emails.additional_status_info,'Unverified') AS b2b_email_additional_status_info,
        COALESCE(production_validated_email_domains.most_recent_additional_email_status_info,'Unverified') AS b2b_domain_status,
        CASE
            WHEN production_validated_emails.status = 'Ok' THEN 'Good'
            WHEN production_validated_emails.status = 'Bad' THEN 'Bad'
            WHEN production_validated_emails.hard_bounce = 1 THEN 'Bad'
            WHEN production_validated_emails.additional_status_info = 'ServerIsCatchAll' THEN 'Catch All'
            WHEN production_validated_emails.id IS NOT NULL THEN 'Unknown'
            WHEN production_validated_email_domains.most_recent_additional_email_status_info IN ('DomainIsInexistent', 'NoMxServersFound') THEN 'Bad'
            WHEN production_validated_email_domains.most_recent_additional_email_status_info = 'ServerIsCatchAll' THEN 'Catch All'
            WHEN production_validated_emails.id IS NULL THEN 'Unverified'
            ELSE 'Unknown'
        END AS b2b_email_status_waterfall,
        production_validated_emails.vendor_status AS b2b_email_vendor_status,
        production_validated_emails.query_type AS b2b_email_query_type,
        production_validated_email_domains.most_recent_office_365 AS b2b_email_domain_office_365,
        ROW_NUMBER() OVER (PARTITION BY production_business_emails.person_id ORDER BY
            DECODE(production_validated_emails.status, 'Ok', 1, 0) DESC,
            DECODE(production_validated_email_domains.most_recent_server_type, 'responds', 0, production_business_emails.best_guess) DESC,
            DECODE(production_validated_email_domains.most_recent_additional_email_status_info, 'ServerIsCatchAll', 1, 0) DESC,
            DECODE(production_validated_emails.status, 'Bad', 1, 0) ASC,
            production_validated_emails.hard_bounce ASC,
            production_business_emails.best_guess DESC,
            production_business_emails.guess_confidence DESC,
            DECODE( production_business_emails.pattern, 'filn', 0, 'ln', 1, 'fn.ln', 2, 'fnln', 3, 'lnfi', 4, 'fnli', 5, 'fn', 6, 'fi.ln', 7, 'fn_ln', 8, 'fn.li', 9, 'fi_ln', 10, 'fn_li', 11, 12) ASC,
            production_business_emails.id ASC) AS row_num
    FROM production_persons
    INNER JOIN production_business_emails ON production_persons.id = production_business_emails.person_id
    LEFT OUTER JOIN production_validated_emails ON production_business_emails.md5 = production_validated_emails.md5
    LEFT OUTER JOIN production_validated_email_domains ON production_business_emails.domain = production_validated_email_domains.email_domain
) t
WHERE row_num = 1
LIMIT 10;

DROP TABLE IF EXISTS export.athena_personal_emails_raw;
CREATE TABLE export.athena_personal_emails_raw (
person_id BIGINT encode raw distkey sortkey,
    p2b_email_1 varchar(1020) encode zstd,
    p2b_email_2 varchar(1020) encode zstd,
    p2b_email_3 varchar(1020) encode zstd,
    p2b_email_4 varchar(1020) encode zstd
)
;

INSERT INTO export.athena_personal_emails_raw 
SELECT person_id,
    SPLIT_PART(grouped_emails, '|', 1) AS p2b_email_1,
    SPLIT_PART(grouped_emails, '|', 2) AS p2b_email_2,
    SPLIT_PART(grouped_emails, '|', 3) AS p2b_email_3,
    SPLIT_PART(grouped_emails, '|', 4) AS p2b_email_4
FROM (
    SELECT t.person_id,
        LISTAGG(t.email, '|') WITHIN GROUP (ORDER BY
            t.onboarded DESC,
            t.confidence DESC,
            t.id ASC) || '||||' AS grouped_emails
    FROM 
        (
            SELECT production_person_consumer_matches.*,
                ROW_NUMBER() OVER (PARTITION BY production_person_consumer_matches.person_id ORDER BY
                    production_person_consumer_matches.onboarded DESC,
                    production_person_consumer_matches.confidence DESC,
                    production_person_consumer_matches.id ASC) AS row_num
            FROM production_person_consumer_matches
        ) t
    WHERE row_num <= 4
    GROUP BY t.person_id
) t
;

DROP TABLE IF EXISTS export.athena_personal_emails_md5;
CREATE TABLE export.athena_personal_emails_md5 (
person_id BIGINT encode raw distkey sortkey,
    p2b_email_1_md5 char(32) encode zstd,
    p2b_email_2_md5 char(32) encode zstd,
    p2b_email_3_md5 char(32) encode zstd,
    p2b_email_4_md5 char(32) encode zstd
)
;

INSERT INTO export.athena_personal_emails_md5
SELECT person_id,
    SPLIT_PART(grouped_emails, '|', 1) AS p2b_email_1_md5,
    SPLIT_PART(grouped_emails, '|', 2) AS p2b_email_2_md5,
    SPLIT_PART(grouped_emails, '|', 3) AS p2b_email_3_md5,
    SPLIT_PART(grouped_emails, '|', 4) AS p2b_email_4_md5
FROM (
    SELECT t.person_id,
        LISTAGG(t.md5, '|') WITHIN GROUP (ORDER BY
            t.onboarded DESC,
            t.confidence DESC,
            t.id ASC) || '||||' AS grouped_emails
    FROM 
        (
            SELECT production_person_consumer_matches.*,
                ROW_NUMBER() OVER (PARTITION BY production_person_consumer_matches.person_id ORDER BY
                    production_person_consumer_matches.onboarded DESC,
                    production_person_consumer_matches.confidence DESC,
                    production_person_consumer_matches.id ASC) AS row_num
            FROM production_person_consumer_matches
        ) t
    WHERE row_num <= 4
    GROUP BY t.person_id
) t
;

DROP TABLE IF EXISTS export.athena_emails_onboarding;
CREATE TABLE export.athena_emails_onboarding (
person_id BIGINT encode raw distkey sortkey,
    email_onboarding_1 varchar(1020) encode zstd,
    email_onboarding_2 varchar(1020) encode zstd,
    email_onboarding_3 varchar(1020) encode zstd,
    email_onboarding_4 varchar(1020) encode zstd,
    email_onboarding_5 varchar(1020) encode zstd,
    email_onboarding_6 varchar(1020) encode zstd,
    email_onboarding_7 varchar(1020) encode zstd,
    email_onboarding_8 varchar(1020) encode zstd,
    email_onboarding_9 varchar(1020) encode zstd
)
;

INSERT INTO export.athena_emails_onboarding
WITH CTE_PERSONAL AS (
    SELECT t.person_id,
        LISTAGG(t.email, '|') WITHIN GROUP (ORDER BY
            t.onboarded DESC,
            t.confidence DESC,
            t.id ASC) AS grouped_emails
    FROM 
        (
            SELECT production_person_consumer_matches.*,
                ROW_NUMBER() OVER (PARTITION BY production_person_consumer_matches.person_id ORDER BY
                    production_person_consumer_matches.onboarded DESC,
                    production_person_consumer_matches.confidence DESC,
                    production_person_consumer_matches.id ASC) AS row_num
            FROM production_person_consumer_matches
        ) t
    WHERE row_num <= 9
    GROUP BY t.person_id
),

CTE_B2B AS (
    SELECT
        production_business_emails.person_id,
        LISTAGG(production_business_emails.email, '|') WITHIN GROUP (ORDER BY
            DECODE(production_validated_emails.status, 'Ok', 1, 0) DESC,
            DECODE(production_validated_email_domains.most_recent_server_type, 'responds', 0, production_business_emails.best_guess) DESC,
            DECODE(production_validated_email_domains.most_recent_additional_email_status_info, 'ServerIsCatchAll', 1, 0) DESC,
            DECODE(production_validated_emails.status, 'Bad', 1, 0) ASC,
            production_validated_emails.hard_bounce ASC,
            production_business_emails.best_guess DESC,
            production_business_emails.guess_confidence DESC,
            DECODE( production_business_emails.pattern, 'filn', 0, 'ln', 1, 'fn.ln', 2, 'fnln', 3, 'lnfi', 4, 'fnli', 5, 'fn', 6, 'fi.ln', 7, 'fn_ln', 8, 'fn.li', 9, 'fi_ln', 10, 'fn_li', 11, 12) ASC,
            production_business_emails.id ASC) AS grouped_emails
    FROM production_business_emails
    LEFT OUTER JOIN production_validated_emails ON production_business_emails.md5 = production_validated_emails.md5
    LEFT OUTER JOIN production_validated_email_domains ON production_business_emails.domain = production_validated_email_domains.email_domain
    GROUP BY production_business_emails.person_id
)

SELECT id,
    SPLIT_PART(t.grouped_emails, '|', 1) AS email_onboarding_1,
    SPLIT_PART(t.grouped_emails, '|', 2) AS email_onboarding_2,
    SPLIT_PART(t.grouped_emails, '|', 3) AS email_onboarding_3,
    SPLIT_PART(t.grouped_emails, '|', 4) AS email_onboarding_4,
    SPLIT_PART(t.grouped_emails, '|', 5) AS email_onboarding_5,
    SPLIT_PART(t.grouped_emails, '|', 6) AS email_onboarding_6,
    SPLIT_PART(t.grouped_emails, '|', 7) AS email_onboarding_7,
    SPLIT_PART(t.grouped_emails, '|', 8) AS email_onboarding_8,
    SPLIT_PART(t.grouped_emails, '|', 9) AS email_onboarding_9
FROM (
    SELECT production_persons.id,
        COALESCE(ctep.grouped_emails || '|', '') || COALESCE(cteb.grouped_emails || '|', '') || '|||||||||' AS grouped_emails
    FROM production_persons
    LEFT OUTER JOIN CTE_PERSONAL ctep ON production_persons.id = ctep.person_id
    LEFT OUTER JOIN CTE_B2B cteb ON production_persons.id = cteb.person_id
    WHERE (ctep.person_id IS NOT NULL OR cteb.person_id IS NOT NULL)
) t
;

CREATE VIEW export.athena_contacts AS 
SELECT
    production_persons.id AS person_id,
    CASE
        WHEN export.athena_b2b_emails.b2b_email <> ''
            AND production_persons.first_name NOT IN ('','"','|','\'')
            AND production_persons.last_name NOT IN ('','"','|','\'')
            AND production_companies.name NOT IN ('','"','|','\'')
            AND production_persons.title NOT IN ('','"','|','\'')
            AND production_persons.company_phone_waterfall NOT IN ('','"','|','\'')
            AND production_persons.company_address1_waterfall NOT IN ('','"','|','\'')
            AND production_persons.company_city_waterfall NOT IN ('','"','|','\'')
            AND production_persons.company_state_waterfall NOT IN ('','"','|','\'')
            AND production_persons.company_zip_waterfall NOT IN ('','"','|','\'')
            THEN 1
        ELSE 0
    END AS full_b2b_contact,
    production_persons.first_name,
    production_persons.last_name,
    production_persons.title,
    production_persons.is_digital_only,
    production_segments.b2b_seniority,
    production_segments.b2b_job_function,
    production_segments.b2b_job_sub_function,
    production_persons.matched_processed_company_id AS production_company_id,
    production_persons.matched_staging_company_id AS staging_company_id,
    production_persons.company_phone_waterfall,
    production_persons.company_address1_waterfall,
    production_persons.company_address2_waterfall,
    production_persons.company_city_waterfall,
    production_persons.company_state_waterfall,
    production_persons.company_state_short_waterfall,
    production_persons.company_zip_waterfall,
    production_persons.company_zip4_waterfall,
    production_persons.company_country_waterfall,
    production_persons.company_phone_local,
    production_persons.company_address1_local,
    production_persons.company_address2_local,
    production_persons.company_city_local,
    production_persons.company_state_local,
    production_persons.company_state_short_local,
    production_persons.company_zip_local,
    production_persons.company_zip4_local,
    production_persons.company_country_local,
    production_companies.phone AS company_phone_headquarters,
    production_companies.address1 AS company_address1_headquarters,
    production_companies.address2 AS company_address2_headquarters,
    production_companies.city AS company_city_headquarters,
    production_companies.state AS company_state_headquarters,
    production_companies.state_short AS company_state_short_headquarters,
    production_companies.zip AS company_zip_headquarters,
    production_companies.zip4 AS company_zip4_headquarters,
    production_companies.country AS company_country_headquarters,
    CASE
        WHEN export.athena_personal_emails_raw.p2b_email_1 <> '' THEN 1
        ELSE 0
    END AS has_raw_personal_email,
    CASE
        WHEN export.athena_personal_emails_md5.p2b_email_1_md5 <> '' THEN 1
        ELSE 0
    END AS has_personal_email,
    production_persons.personal_phone,
    production_persons.personal_address1,
    production_persons.personal_address2,
    production_persons.personal_city,
    production_persons.personal_state,
    production_persons.personal_state_short,
    production_persons.personal_zip,
    production_persons.personal_zip4,
    production_persons.personal_country,
    CASE
        WHEN export.athena_personal_emails_md5.p2b_email_1_md5 <> ''
            AND production_persons.personal_address1 NOT IN ('','"','|','\'')
            AND production_persons.personal_zip NOT IN ('','"','|','\'')
            THEN 1
        ELSE 0
    END AS full_personal_connection,
    production_persons.current_position_start_year,
    production_persons.declared_city,
    production_persons.declared_company_city,
    production_persons.declared_company_name,
    production_persons.declared_company_state,
    production_persons.declared_country,
    production_persons.declared_state,
    production_persons.education_1_graduation_year,
    production_persons.education_1_institution,
    production_persons.education_1_level,
    production_persons.education_1_start_year,
    production_persons.education_2_graduation_year,
    production_persons.education_2_institution,
    production_persons.education_2_level,
    production_persons.education_2_start_year,
    production_persons.education_earliest_graduation_year,
    production_persons.education_earliest_level,
    production_persons.language1,
    production_persons.language2,
    production_persons.language3,
    production_persons.last_processed,
    production_persons.last_updated,
    production_persons.linkedin_company_id,
    production_persons.linkedin_company_url_path,
    production_persons.previous_position_1_company_name,
    production_persons.previous_position_1_industry,
    production_persons.previous_position_1_start_year,
    production_persons.previous_position_1_title,
    production_persons.previous_position_2_company_name,
    production_persons.previous_position_2_industry,
    production_persons.previous_position_2_start_year,
    production_persons.previous_position_2_title,
    production_persons.provider_id,
    production_persons.provider_record_id,
    production_persons.skill1,
    production_persons.skill2,
    production_persons.skill3,
    production_persons.skill4,
    production_persons.skill5,
    production_persons.source_id,
    production_persons.source_record_id,
    production_persons.source_url,
    production_persons.linkedin_profile_url,
    production_persons.linkedin_profile_url_path,
    production_companies.source_id AS company_source_id,
    production_companies.provider_id AS company_provider_id,
    production_persons.number_of_connections,
    production_companies.num_processed_matches AS company_num_processed_matches,
    production_companies.name AS company_name,
    production_companies.domain AS company_domain,
    production_companies.website AS company_website,
    production_companies.employees AS company_employees,
    production_companies.employees_bucket AS company_employees_bucket,
    production_companies.revenue AS company_revenue,
    production_companies.revenue_bucket AS company_revenue_bucket,
    production_companies.primary_industry AS company_primary_industry,
    production_companies.primary_sic_code AS company_primary_sic_code,
    production_companies.primary_naics_code AS company_primary_naics_code,
    export.athena_b2b_emails.b2b_email,
    export.athena_b2b_emails.b2b_email_md5,
    export.athena_b2b_emails.b2b_email_status,
    export.athena_b2b_emails.b2b_email_additional_status_info,
    export.athena_b2b_emails.b2b_domain_status AS b2b_domain_email_status,
    export.athena_b2b_emails.b2b_email_status_waterfall,
    export.athena_b2b_emails.b2b_email_vendor_status,
    export.athena_b2b_emails.b2b_email_query_type,
    export.athena_b2b_emails.b2b_email_domain_office_365,
    export.athena_personal_emails_raw.p2b_email_1,
    export.athena_personal_emails_raw.p2b_email_2,
    export.athena_personal_emails_raw.p2b_email_3,
    export.athena_personal_emails_raw.p2b_email_4,
    export.athena_personal_emails_md5.p2b_email_1_md5,
    export.athena_personal_emails_md5.p2b_email_2_md5,
    export.athena_personal_emails_md5.p2b_email_3_md5,
    export.athena_personal_emails_md5.p2b_email_4_md5,
    export.athena_emails_onboarding.email_onboarding_1,
    export.athena_emails_onboarding.email_onboarding_2,
    export.athena_emails_onboarding.email_onboarding_3,
    export.athena_emails_onboarding.email_onboarding_4,
    export.athena_emails_onboarding.email_onboarding_5,
    export.athena_emails_onboarding.email_onboarding_6,
    export.athena_emails_onboarding.email_onboarding_7,
    export.athena_emails_onboarding.email_onboarding_8,
    export.athena_emails_onboarding.email_onboarding_9,
    CAST(NULLIF(production_segments.b2b_company_fortune_1000, 0) AS SMALLINT) AS b2b_company_fortune_1000,
    CAST(NULLIF(production_segments.b2b_company_fortune_500, 0) AS SMALLINT) AS b2b_company_fortune_500,
    CAST(NULLIF(production_segments.b2b_company_revenue_large, 0) AS SMALLINT) AS b2b_company_revenue_large,
    CAST(NULLIF(production_segments.b2b_company_revenue_med, 0) AS SMALLINT) AS b2b_company_revenue_med,
    CAST(NULLIF(production_segments.b2b_company_revenue_med_large, 0) AS SMALLINT) AS b2b_company_revenue_med_large,
    CAST(NULLIF(production_segments.b2b_company_revenue_micro, 0) AS SMALLINT) AS b2b_company_revenue_micro,
    CAST(NULLIF(production_segments.b2b_company_revenue_small, 0) AS SMALLINT) AS b2b_company_revenue_small,
    CAST(NULLIF(production_segments.b2b_company_revenue_xlarge, 0) AS SMALLINT) AS b2b_company_revenue_xlarge,
    production_segments.b2b_company_size,
    CAST(NULLIF(production_segments.b2b_company_size_large, 0) AS SMALLINT) AS b2b_company_size_large,
    CAST(NULLIF(production_segments.b2b_company_size_med, 0) AS SMALLINT) AS b2b_company_size_med,
    CAST(NULLIF(production_segments.b2b_company_size_med_large, 0) AS SMALLINT) AS b2b_company_size_med_large,
    CAST(NULLIF(production_segments.b2b_company_size_micro, 0) AS SMALLINT) AS b2b_company_size_micro,
    CAST(NULLIF(production_segments.b2b_company_size_small, 0) AS SMALLINT) AS b2b_company_size_small,
    CAST(NULLIF(production_segments.b2b_company_size_xlarge, 0) AS SMALLINT) AS b2b_company_size_xlarge,
    CAST(NULLIF(production_segments.b2b_engineering_decision_makers, 0) AS SMALLINT) AS b2b_engineering_decision_makers,
    CAST(NULLIF(production_segments.b2b_engineering_executives, 0) AS SMALLINT) AS b2b_engineering_executives,
    CAST(NULLIF(production_segments.b2b_engineering_managers, 0) AS SMALLINT) AS b2b_engineering_managers,
    CAST(NULLIF(production_segments.b2b_fa_admin, 0) AS SMALLINT) AS b2b_fa_admin,
    CAST(NULLIF(production_segments.b2b_fa_admin_administrator, 0) AS SMALLINT) AS b2b_fa_admin_administrator,
    CAST(NULLIF(production_segments.b2b_fa_admin_assistant, 0) AS SMALLINT) AS b2b_fa_admin_assistant,
    CAST(NULLIF(production_segments.b2b_fa_admin_office_manager, 0) AS SMALLINT) AS b2b_fa_admin_office_manager,
    CAST(NULLIF(production_segments.b2b_fa_admin_secretary, 0) AS SMALLINT) AS b2b_fa_admin_secretary,
    CAST(NULLIF(production_segments.b2b_fa_admin_typist, 0) AS SMALLINT) AS b2b_fa_admin_typist,
    CAST(NULLIF(production_segments.b2b_fa_consultants, 0) AS SMALLINT) AS b2b_fa_consultants,
    CAST(NULLIF(production_segments.b2b_fa_education, 0) AS SMALLINT) AS b2b_fa_education,
    CAST(NULLIF(production_segments.b2b_fa_education_admissions, 0) AS SMALLINT) AS b2b_fa_education_admissions,
    CAST(NULLIF(production_segments.b2b_fa_education_librarian, 0) AS SMALLINT) AS b2b_fa_education_librarian,
    CAST(NULLIF(production_segments.b2b_fa_education_professor, 0) AS SMALLINT) AS b2b_fa_education_professor,
    CAST(NULLIF(production_segments.b2b_fa_education_teacher, 0) AS SMALLINT) AS b2b_fa_education_teacher,
    CAST(NULLIF(production_segments.b2b_fa_engineering, 0) AS SMALLINT) AS b2b_fa_engineering,
    CAST(NULLIF(production_segments.b2b_fa_engineering_biomedical, 0) AS SMALLINT) AS b2b_fa_engineering_biomedical,
    CAST(NULLIF(production_segments.b2b_fa_engineering_chemical, 0) AS SMALLINT) AS b2b_fa_engineering_chemical,
    CAST(NULLIF(production_segments.b2b_fa_engineering_civil, 0) AS SMALLINT) AS b2b_fa_engineering_civil,
    CAST(NULLIF(production_segments.b2b_fa_engineering_electrical, 0) AS SMALLINT) AS b2b_fa_engineering_electrical,
    CAST(NULLIF(production_segments.b2b_fa_engineering_electronics, 0) AS SMALLINT) AS b2b_fa_engineering_electronics,
    CAST(NULLIF(production_segments.b2b_fa_engineering_industrial, 0) AS SMALLINT) AS b2b_fa_engineering_industrial,
    CAST(NULLIF(production_segments.b2b_fa_engineering_mechanical, 0) AS SMALLINT) AS b2b_fa_engineering_mechanical,
    CAST(NULLIF(production_segments.b2b_fa_finance, 0) AS SMALLINT) AS b2b_fa_finance,
    CAST(NULLIF(production_segments.b2b_fa_finance_accounting, 0) AS SMALLINT) AS b2b_fa_finance_accounting,
    CAST(NULLIF(production_segments.b2b_fa_finance_analyst, 0) AS SMALLINT) AS b2b_fa_finance_analyst,
    CAST(NULLIF(production_segments.b2b_fa_finance_audit, 0) AS SMALLINT) AS b2b_fa_finance_audit,
    CAST(NULLIF(production_segments.b2b_fa_finance_banking, 0) AS SMALLINT) AS b2b_fa_finance_banking,
    CAST(NULLIF(production_segments.b2b_fa_finance_cfp, 0) AS SMALLINT) AS b2b_fa_finance_cfp,
    CAST(NULLIF(production_segments.b2b_fa_finance_compliance_specialist, 0) AS SMALLINT) AS b2b_fa_finance_compliance_specialist,
    CAST(NULLIF(production_segments.b2b_fa_finance_corporate, 0) AS SMALLINT) AS b2b_fa_finance_corporate,
    CAST(NULLIF(production_segments.b2b_fa_finance_cpa, 0) AS SMALLINT) AS b2b_fa_finance_cpa,
    CAST(NULLIF(production_segments.b2b_fa_finance_economist, 0) AS SMALLINT) AS b2b_fa_finance_economist,
    CAST(NULLIF(production_segments.b2b_fa_finance_investment_banking, 0) AS SMALLINT) AS b2b_fa_finance_investment_banking,
    CAST(NULLIF(production_segments.b2b_fa_finance_mortgage_specialist, 0) AS SMALLINT) AS b2b_fa_finance_mortgage_specialist,
    CAST(NULLIF(production_segments.b2b_fa_finance_risk_management, 0) AS SMALLINT) AS b2b_fa_finance_risk_management,
    CAST(NULLIF(production_segments.b2b_fa_finance_statistician, 0) AS SMALLINT) AS b2b_fa_finance_statistician,
    CAST(NULLIF(production_segments.b2b_fa_finance_tax_specialist, 0) AS SMALLINT) AS b2b_fa_finance_tax_specialist,
    CAST(NULLIF(production_segments.b2b_fa_finance_treasurer, 0) AS SMALLINT) AS b2b_fa_finance_treasurer,
    CAST(NULLIF(production_segments.b2b_fa_finance_wealth_management, 0) AS SMALLINT) AS b2b_fa_finance_wealth_management,
    CAST(NULLIF(production_segments.b2b_fa_general_management, 0) AS SMALLINT) AS b2b_fa_general_management,
    CAST(NULLIF(production_segments.b2b_fa_general_management_board_member, 0) AS SMALLINT) AS b2b_fa_general_management_board_member,
    CAST(NULLIF(production_segments.b2b_fa_general_management_ceo, 0) AS SMALLINT) AS b2b_fa_general_management_ceo,
    CAST(NULLIF(production_segments.b2b_fa_general_management_cfo, 0) AS SMALLINT) AS b2b_fa_general_management_cfo,
    CAST(NULLIF(production_segments.b2b_fa_general_management_cio, 0) AS SMALLINT) AS b2b_fa_general_management_cio,
    CAST(NULLIF(production_segments.b2b_fa_general_management_cmo, 0) AS SMALLINT) AS b2b_fa_general_management_cmo,
    CAST(NULLIF(production_segments.b2b_fa_general_management_coo, 0) AS SMALLINT) AS b2b_fa_general_management_coo,
    CAST(NULLIF(production_segments.b2b_fa_general_management_cto, 0) AS SMALLINT) AS b2b_fa_general_management_cto,
    CAST(NULLIF(production_segments.b2b_fa_general_management_director, 0) AS SMALLINT) AS b2b_fa_general_management_director,
    CAST(NULLIF(production_segments.b2b_fa_general_management_executive_vp, 0) AS SMALLINT) AS b2b_fa_general_management_executive_vp,
    CAST(NULLIF(production_segments.b2b_fa_general_management_founder, 0) AS SMALLINT) AS b2b_fa_general_management_founder,
    CAST(NULLIF(production_segments.b2b_fa_general_management_manager_or_supervisor, 0) AS SMALLINT) AS b2b_fa_general_management_manager_or_supervisor,
    CAST(NULLIF(production_segments.b2b_fa_general_management_owner, 0) AS SMALLINT) AS b2b_fa_general_management_owner,
    CAST(NULLIF(production_segments.b2b_fa_general_management_partner, 0) AS SMALLINT) AS b2b_fa_general_management_partner,
    CAST(NULLIF(production_segments.b2b_fa_general_management_president, 0) AS SMALLINT) AS b2b_fa_general_management_president,
    CAST(NULLIF(production_segments.b2b_fa_general_management_senior_board_member, 0) AS SMALLINT) AS b2b_fa_general_management_senior_board_member,
    CAST(NULLIF(production_segments.b2b_fa_general_management_vp, 0) AS SMALLINT) AS b2b_fa_general_management_vp,
    CAST(NULLIF(production_segments.b2b_fa_government, 0) AS SMALLINT) AS b2b_fa_government,
    CAST(NULLIF(production_segments.b2b_fa_government_elected_officials, 0) AS SMALLINT) AS b2b_fa_government_elected_officials,
    CAST(NULLIF(production_segments.b2b_fa_healthcare, 0) AS SMALLINT) AS b2b_fa_healthcare,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_chiropractor, 0) AS SMALLINT) AS b2b_fa_healthcare_chiropractor,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_dental_assistant, 0) AS SMALLINT) AS b2b_fa_healthcare_dental_assistant,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_dental_hygenist, 0) AS SMALLINT) AS b2b_fa_healthcare_dental_hygenist,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_dentist, 0) AS SMALLINT) AS b2b_fa_healthcare_dentist,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_dietician, 0) AS SMALLINT) AS b2b_fa_healthcare_dietician,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_healthcare_professional, 0) AS SMALLINT) AS b2b_fa_healthcare_healthcare_professional,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_nurse, 0) AS SMALLINT) AS b2b_fa_healthcare_nurse,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_opticians, 0) AS SMALLINT) AS b2b_fa_healthcare_opticians,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_optometrist, 0) AS SMALLINT) AS b2b_fa_healthcare_optometrist,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_paramedic, 0) AS SMALLINT) AS b2b_fa_healthcare_paramedic,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_pharmaceuticals, 0) AS SMALLINT) AS b2b_fa_healthcare_pharmaceuticals,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_pharmacist, 0) AS SMALLINT) AS b2b_fa_healthcare_pharmacist,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_physical_therapist, 0) AS SMALLINT) AS b2b_fa_healthcare_physical_therapist,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_physician_or_doctor, 0) AS SMALLINT) AS b2b_fa_healthcare_physician_or_doctor,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_physicians_assistant, 0) AS SMALLINT) AS b2b_fa_healthcare_physicians_assistant,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_psychologist, 0) AS SMALLINT) AS b2b_fa_healthcare_psychologist,
    CAST(NULLIF(production_segments.b2b_fa_healthcare_therapist, 0) AS SMALLINT) AS b2b_fa_healthcare_therapist,
    CAST(NULLIF(production_segments.b2b_fa_human_resources, 0) AS SMALLINT) AS b2b_fa_human_resources,
    CAST(NULLIF(production_segments.b2b_fa_human_resources_benefits_and_compensation, 0) AS SMALLINT) AS b2b_fa_human_resources_benefits_and_compensation,
    CAST(NULLIF(production_segments.b2b_fa_human_resources_employee_development, 0) AS SMALLINT) AS b2b_fa_human_resources_employee_development,
    CAST(NULLIF(production_segments.b2b_fa_human_resources_payroll_specialist, 0) AS SMALLINT) AS b2b_fa_human_resources_payroll_specialist,
    CAST(NULLIF(production_segments.b2b_fa_human_resources_recruiting, 0) AS SMALLINT) AS b2b_fa_human_resources_recruiting,
    CAST(NULLIF(production_segments.b2b_fa_law_enforcement, 0) AS SMALLINT) AS b2b_fa_law_enforcement,
    CAST(NULLIF(production_segments.b2b_fa_law_enforcement_correctional_workers, 0) AS SMALLINT) AS b2b_fa_law_enforcement_correctional_workers,
    CAST(NULLIF(production_segments.b2b_fa_law_enforcement_parole_officer, 0) AS SMALLINT) AS b2b_fa_law_enforcement_parole_officer,
    CAST(NULLIF(production_segments.b2b_fa_law_enforcement_police, 0) AS SMALLINT) AS b2b_fa_law_enforcement_police,
    CAST(NULLIF(production_segments.b2b_fa_legal, 0) AS SMALLINT) AS b2b_fa_legal,
    CAST(NULLIF(production_segments.b2b_fa_legal_judge, 0) AS SMALLINT) AS b2b_fa_legal_judge,
    CAST(NULLIF(production_segments.b2b_fa_legal_lawyer, 0) AS SMALLINT) AS b2b_fa_legal_lawyer,
    CAST(NULLIF(production_segments.b2b_fa_legal_paralegal, 0) AS SMALLINT) AS b2b_fa_legal_paralegal,
    CAST(NULLIF(production_segments.b2b_fa_legal_prosecutor, 0) AS SMALLINT) AS b2b_fa_legal_prosecutor,
    CAST(NULLIF(production_segments.b2b_fa_marketing, 0) AS SMALLINT) AS b2b_fa_marketing,
    CAST(NULLIF(production_segments.b2b_fa_marketing_advertising, 0) AS SMALLINT) AS b2b_fa_marketing_advertising,
    CAST(NULLIF(production_segments.b2b_fa_marketing_creative, 0) AS SMALLINT) AS b2b_fa_marketing_creative,
    CAST(NULLIF(production_segments.b2b_fa_marketing_events, 0) AS SMALLINT) AS b2b_fa_marketing_events,
    CAST(NULLIF(production_segments.b2b_fa_marketing_marketing_communications, 0) AS SMALLINT) AS b2b_fa_marketing_marketing_communications,
    CAST(NULLIF(production_segments.b2b_fa_military, 0) AS SMALLINT) AS b2b_fa_military,
    CAST(NULLIF(production_segments.b2b_fa_military_air_force, 0) AS SMALLINT) AS b2b_fa_military_air_force,
    CAST(NULLIF(production_segments.b2b_fa_military_army, 0) AS SMALLINT) AS b2b_fa_military_army,
    CAST(NULLIF(production_segments.b2b_fa_military_coast_guard, 0) AS SMALLINT) AS b2b_fa_military_coast_guard,
    CAST(NULLIF(production_segments.b2b_fa_military_marines, 0) AS SMALLINT) AS b2b_fa_military_marines,
    CAST(NULLIF(production_segments.b2b_fa_military_navy, 0) AS SMALLINT) AS b2b_fa_military_navy,
    CAST(NULLIF(production_segments.b2b_fa_operations, 0) AS SMALLINT) AS b2b_fa_operations,
    CAST(NULLIF(production_segments.b2b_fa_operations_environmental, 0) AS SMALLINT) AS b2b_fa_operations_environmental,
    CAST(NULLIF(production_segments.b2b_fa_operations_facility_maintenance, 0) AS SMALLINT) AS b2b_fa_operations_facility_maintenance,
    CAST(NULLIF(production_segments.b2b_fa_operations_food_and_beverage, 0) AS SMALLINT) AS b2b_fa_operations_food_and_beverage,
    CAST(NULLIF(production_segments.b2b_fa_operations_manufacturing, 0) AS SMALLINT) AS b2b_fa_operations_manufacturing,
    CAST(NULLIF(production_segments.b2b_fa_operations_quality_assurance, 0) AS SMALLINT) AS b2b_fa_operations_quality_assurance,
    CAST(NULLIF(production_segments.b2b_fa_operations_records_management, 0) AS SMALLINT) AS b2b_fa_operations_records_management,
    CAST(NULLIF(production_segments.b2b_fa_operations_safety, 0) AS SMALLINT) AS b2b_fa_operations_safety,
    CAST(NULLIF(production_segments.b2b_fa_operations_training, 0) AS SMALLINT) AS b2b_fa_operations_training,
    CAST(NULLIF(production_segments.b2b_fa_photographer, 0) AS SMALLINT) AS b2b_fa_photographer,
    CAST(NULLIF(production_segments.b2b_fa_real_estate, 0) AS SMALLINT) AS b2b_fa_real_estate,
    CAST(NULLIF(production_segments.b2b_fa_real_estate_architect, 0) AS SMALLINT) AS b2b_fa_real_estate_architect,
    CAST(NULLIF(production_segments.b2b_fa_real_estate_builder, 0) AS SMALLINT) AS b2b_fa_real_estate_builder,
    CAST(NULLIF(production_segments.b2b_fa_real_estate_contractor, 0) AS SMALLINT) AS b2b_fa_real_estate_contractor,
    CAST(NULLIF(production_segments.b2b_fa_real_estate_developer, 0) AS SMALLINT) AS b2b_fa_real_estate_developer,
    CAST(NULLIF(production_segments.b2b_fa_real_estate_mortgage_specialist, 0) AS SMALLINT) AS b2b_fa_real_estate_mortgage_specialist,
    CAST(NULLIF(production_segments.b2b_fa_real_estate_real_estate_agent, 0) AS SMALLINT) AS b2b_fa_real_estate_real_estate_agent,
    CAST(NULLIF(production_segments.b2b_fa_religious_leader, 0) AS SMALLINT) AS b2b_fa_religious_leader,
    CAST(NULLIF(production_segments.b2b_fa_research_and_development, 0) AS SMALLINT) AS b2b_fa_research_and_development,
    CAST(NULLIF(production_segments.b2b_fa_research_and_development_product_development, 0) AS SMALLINT) AS b2b_fa_research_and_development_product_development,
    CAST(NULLIF(production_segments.b2b_fa_research_and_development_project_management, 0) AS SMALLINT) AS b2b_fa_research_and_development_project_management,
    CAST(NULLIF(production_segments.b2b_fa_research_and_development_research, 0) AS SMALLINT) AS b2b_fa_research_and_development_research,
    CAST(NULLIF(production_segments.b2b_fa_retired, 0) AS SMALLINT) AS b2b_fa_retired,
    CAST(NULLIF(production_segments.b2b_fa_sales, 0) AS SMALLINT) AS b2b_fa_sales,
    CAST(NULLIF(production_segments.b2b_fa_sales_account_management, 0) AS SMALLINT) AS b2b_fa_sales_account_management,
    CAST(NULLIF(production_segments.b2b_fa_sales_business_development, 0) AS SMALLINT) AS b2b_fa_sales_business_development,
    CAST(NULLIF(production_segments.b2b_fa_sales_community_development, 0) AS SMALLINT) AS b2b_fa_sales_community_development,
    CAST(NULLIF(production_segments.b2b_fa_sales_customer_service, 0) AS SMALLINT) AS b2b_fa_sales_customer_service,
    CAST(NULLIF(production_segments.b2b_fa_science, 0) AS SMALLINT) AS b2b_fa_science,
    CAST(NULLIF(production_segments.b2b_fa_science_chemist, 0) AS SMALLINT) AS b2b_fa_science_chemist,
    CAST(NULLIF(production_segments.b2b_fa_science_geologist, 0) AS SMALLINT) AS b2b_fa_science_geologist,
    CAST(NULLIF(production_segments.b2b_fa_science_scientists, 0) AS SMALLINT) AS b2b_fa_science_scientists,
    CAST(NULLIF(production_segments.b2b_fa_stay_at_home_parent, 0) AS SMALLINT) AS b2b_fa_stay_at_home_parent,
    CAST(NULLIF(production_segments.b2b_fa_student, 0) AS SMALLINT) AS b2b_fa_student,
    CAST(NULLIF(production_segments.b2b_fa_supply_chain, 0) AS SMALLINT) AS b2b_fa_supply_chain,
    CAST(NULLIF(production_segments.b2b_fa_supply_chain_logistics, 0) AS SMALLINT) AS b2b_fa_supply_chain_logistics,
    CAST(NULLIF(production_segments.b2b_fa_supply_chain_procurement, 0) AS SMALLINT) AS b2b_fa_supply_chain_procurement,
    CAST(NULLIF(production_segments.b2b_fa_supply_chain_sourcing, 0) AS SMALLINT) AS b2b_fa_supply_chain_sourcing,
    CAST(NULLIF(production_segments.b2b_fa_technology, 0) AS SMALLINT) AS b2b_fa_technology,
    CAST(NULLIF(production_segments.b2b_fa_technology_computing, 0) AS SMALLINT) AS b2b_fa_technology_computing,
    CAST(NULLIF(production_segments.b2b_fa_technology_data_management, 0) AS SMALLINT) AS b2b_fa_technology_data_management,
    CAST(NULLIF(production_segments.b2b_fa_technology_dba, 0) AS SMALLINT) AS b2b_fa_technology_dba,
    CAST(NULLIF(production_segments.b2b_fa_technology_information_security, 0) AS SMALLINT) AS b2b_fa_technology_information_security,
    CAST(NULLIF(production_segments.b2b_fa_technology_information_technology, 0) AS SMALLINT) AS b2b_fa_technology_information_technology,
    CAST(NULLIF(production_segments.b2b_fa_technology_mis, 0) AS SMALLINT) AS b2b_fa_technology_mis,
    CAST(NULLIF(production_segments.b2b_fa_technology_network_administration, 0) AS SMALLINT) AS b2b_fa_technology_network_administration,
    CAST(NULLIF(production_segments.b2b_fa_technology_quality_assurance, 0) AS SMALLINT) AS b2b_fa_technology_quality_assurance,
    CAST(NULLIF(production_segments.b2b_fa_technology_software, 0) AS SMALLINT) AS b2b_fa_technology_software,
    CAST(NULLIF(production_segments.b2b_fa_technology_systems_admin, 0) AS SMALLINT) AS b2b_fa_technology_systems_admin,
    CAST(NULLIF(production_segments.b2b_fa_technology_technical_support, 0) AS SMALLINT) AS b2b_fa_technology_technical_support,
    CAST(NULLIF(production_segments.b2b_fa_technology_telecom, 0) AS SMALLINT) AS b2b_fa_technology_telecom,
    CAST(NULLIF(production_segments.b2b_fa_technology_web_development, 0) AS SMALLINT) AS b2b_fa_technology_web_development,
    CAST(NULLIF(production_segments.b2b_fa_writer, 0) AS SMALLINT) AS b2b_fa_writer,
    CAST(NULLIF(production_segments.b2b_finance_decision_makers, 0) AS SMALLINT) AS b2b_finance_decision_makers,
    CAST(NULLIF(production_segments.b2b_finance_executives, 0) AS SMALLINT) AS b2b_finance_executives,
    CAST(NULLIF(production_segments.b2b_finance_managers, 0) AS SMALLINT) AS b2b_finance_managers,
    CAST(NULLIF(production_segments.b2b_healthcare_decision_makers, 0) AS SMALLINT) AS b2b_healthcare_decision_makers,
    CAST(NULLIF(production_segments.b2b_healthcare_executives, 0) AS SMALLINT) AS b2b_healthcare_executives,
    CAST(NULLIF(production_segments.b2b_healthcare_managers, 0) AS SMALLINT) AS b2b_healthcare_managers,
    CAST(NULLIF(production_segments.b2b_hr_decision_makers, 0) AS SMALLINT) AS b2b_hr_decision_makers,
    CAST(NULLIF(production_segments.b2b_hr_executives, 0) AS SMALLINT) AS b2b_hr_executives,
    CAST(NULLIF(production_segments.b2b_hr_managers, 0) AS SMALLINT) AS b2b_hr_managers,
    CAST(NULLIF(production_segments.b2b_ind_agriculture, 0) AS SMALLINT) AS b2b_ind_agriculture,
    CAST(NULLIF(production_segments.b2b_ind_apparel, 0) AS SMALLINT) AS b2b_ind_apparel,
    CAST(NULLIF(production_segments.b2b_ind_automotive, 0) AS SMALLINT) AS b2b_ind_automotive,
    CAST(NULLIF(production_segments.b2b_ind_business_services, 0) AS SMALLINT) AS b2b_ind_business_services,
    CAST(NULLIF(production_segments.b2b_ind_business_services_adv_marketing, 0) AS SMALLINT) AS b2b_ind_business_services_adv_marketing,
    CAST(NULLIF(production_segments.b2b_ind_construction, 0) AS SMALLINT) AS b2b_ind_construction,
    CAST(NULLIF(production_segments.b2b_ind_consumer_services, 0) AS SMALLINT) AS b2b_ind_consumer_services,
    CAST(NULLIF(production_segments.b2b_ind_education, 0) AS SMALLINT) AS b2b_ind_education,
    CAST(NULLIF(production_segments.b2b_ind_education_colleges_univ, 0) AS SMALLINT) AS b2b_ind_education_colleges_univ,
    CAST(NULLIF(production_segments.b2b_ind_energy_and_utilities, 0) AS SMALLINT) AS b2b_ind_energy_and_utilities,
    CAST(NULLIF(production_segments.b2b_ind_finance, 0) AS SMALLINT) AS b2b_ind_finance,
    CAST(NULLIF(production_segments.b2b_ind_finance_investment_banking, 0) AS SMALLINT) AS b2b_ind_finance_investment_banking,
    CAST(NULLIF(production_segments.b2b_ind_food_and_beverages, 0) AS SMALLINT) AS b2b_ind_food_and_beverages,
    CAST(NULLIF(production_segments.b2b_ind_government, 0) AS SMALLINT) AS b2b_ind_government,
    CAST(NULLIF(production_segments.b2b_ind_healthcare, 0) AS SMALLINT) AS b2b_ind_healthcare,
    CAST(NULLIF(production_segments.b2b_ind_healthcare_hosp_clinics, 0) AS SMALLINT) AS b2b_ind_healthcare_hosp_clinics,
    CAST(NULLIF(production_segments.b2b_ind_healthcare_insurance, 0) AS SMALLINT) AS b2b_ind_healthcare_insurance,
    CAST(NULLIF(production_segments.b2b_ind_hospitality_and_hotels, 0) AS SMALLINT) AS b2b_ind_hospitality_and_hotels,
    CAST(NULLIF(production_segments.b2b_ind_information_technology, 0) AS SMALLINT) AS b2b_ind_information_technology,
    CAST(NULLIF(production_segments.b2b_ind_insurance, 0) AS SMALLINT) AS b2b_ind_insurance,
    CAST(NULLIF(production_segments.b2b_ind_legal, 0) AS SMALLINT) AS b2b_ind_legal,
    CAST(NULLIF(production_segments.b2b_ind_manufacturing, 0) AS SMALLINT) AS b2b_ind_manufacturing,
    CAST(NULLIF(production_segments.b2b_ind_media, 0) AS SMALLINT) AS b2b_ind_media,
    CAST(NULLIF(production_segments.b2b_ind_media_internet, 0) AS SMALLINT) AS b2b_ind_media_internet,
    CAST(NULLIF(production_segments.b2b_ind_mining, 0) AS SMALLINT) AS b2b_ind_mining,
    CAST(NULLIF(production_segments.b2b_ind_non_profit, 0) AS SMALLINT) AS b2b_ind_non_profit,
    CAST(NULLIF(production_segments.b2b_ind_oil_and_gas, 0) AS SMALLINT) AS b2b_ind_oil_and_gas,
    CAST(NULLIF(production_segments.b2b_ind_pharmaceutical, 0) AS SMALLINT) AS b2b_ind_pharmaceutical,
    CAST(NULLIF(production_segments.b2b_ind_real_estate, 0) AS SMALLINT) AS b2b_ind_real_estate,
    CAST(NULLIF(production_segments.b2b_ind_real_estate_residential, 0) AS SMALLINT) AS b2b_ind_real_estate_residential,
    CAST(NULLIF(production_segments.b2b_ind_religious_services, 0) AS SMALLINT) AS b2b_ind_religious_services,
    CAST(NULLIF(production_segments.b2b_ind_retail, 0) AS SMALLINT) AS b2b_ind_retail,
    CAST(NULLIF(production_segments.b2b_ind_software, 0) AS SMALLINT) AS b2b_ind_software,
    CAST(NULLIF(production_segments.b2b_ind_software_security, 0) AS SMALLINT) AS b2b_ind_software_security,
    CAST(NULLIF(production_segments.b2b_ind_sports_and_rec, 0) AS SMALLINT) AS b2b_ind_sports_and_rec,
    CAST(NULLIF(production_segments.b2b_ind_telecom, 0) AS SMALLINT) AS b2b_ind_telecom,
    CAST(NULLIF(production_segments.b2b_ind_transportation, 0) AS SMALLINT) AS b2b_ind_transportation,
    CAST(NULLIF(production_segments.b2b_ind_travel, 0) AS SMALLINT) AS b2b_ind_travel,
    CAST(NULLIF(production_segments.b2b_ind_waste_services, 0) AS SMALLINT) AS b2b_ind_waste_services,
    CAST(NULLIF(production_segments.b2b_ind_wholesalers, 0) AS SMALLINT) AS b2b_ind_wholesalers,
    CAST(NULLIF(production_segments.b2b_leadership_business_decision_maker, 0) AS SMALLINT) AS b2b_leadership_business_decision_maker,
    CAST(NULLIF(production_segments.b2b_leadership_female_owner, 0) AS SMALLINT) AS b2b_leadership_female_owner,
    CAST(NULLIF(production_segments.b2b_leadership_minority_owner, 0) AS SMALLINT) AS b2b_leadership_minority_owner,
    CAST(NULLIF(production_segments.b2b_leadership_senior_board_members, 0) AS SMALLINT) AS b2b_leadership_senior_board_members,
    CAST(NULLIF(production_segments.b2b_leadership_senior_executives, 0) AS SMALLINT) AS b2b_leadership_senior_executives,
    CAST(NULLIF(production_segments.b2b_leadership_senior_management, 0) AS SMALLINT) AS b2b_leadership_senior_management,
    CAST(NULLIF(production_segments.b2b_leadership_small_biz_owner, 0) AS SMALLINT) AS b2b_leadership_small_biz_owner,
    CAST(NULLIF(production_segments.b2b_leadership_vp_plus, 0) AS SMALLINT) AS b2b_leadership_vp_plus,
    CAST(NULLIF(production_segments.b2b_marketing_decision_makers, 0) AS SMALLINT) AS b2b_marketing_decision_makers,
    CAST(NULLIF(production_segments.b2b_marketing_executives, 0) AS SMALLINT) AS b2b_marketing_executives,
    CAST(NULLIF(production_segments.b2b_marketing_managers, 0) AS SMALLINT) AS b2b_marketing_managers,
    CAST(NULLIF(production_segments.b2b_operations_decision_makers, 0) AS SMALLINT) AS b2b_operations_decision_makers,
    CAST(NULLIF(production_segments.b2b_operations_executives, 0) AS SMALLINT) AS b2b_operations_executives,
    CAST(NULLIF(production_segments.b2b_operations_managers, 0) AS SMALLINT) AS b2b_operations_managers,
    CAST(NULLIF(production_segments.b2b_r_and_d_decision_makers, 0) AS SMALLINT) AS b2b_r_and_d_decision_makers,
    CAST(NULLIF(production_segments.b2b_r_and_d_executives, 0) AS SMALLINT) AS b2b_r_and_d_executives,
    CAST(NULLIF(production_segments.b2b_r_and_d_managers, 0) AS SMALLINT) AS b2b_r_and_d_managers,
    CAST(NULLIF(production_segments.b2b_sales_decision_makers, 0) AS SMALLINT) AS b2b_sales_decision_makers,
    CAST(NULLIF(production_segments.b2b_sales_executives, 0) AS SMALLINT) AS b2b_sales_executives,
    CAST(NULLIF(production_segments.b2b_sales_managers, 0) AS SMALLINT) AS b2b_sales_managers,
    production_segments.b2b_sales_volume,
    CAST(NULLIF(production_segments.b2b_seniority_advisors, 0) AS SMALLINT) AS b2b_seniority_advisors,
    CAST(NULLIF(production_segments.b2b_seniority_board_of_directors, 0) AS SMALLINT) AS b2b_seniority_board_of_directors,
    CAST(NULLIF(production_segments.b2b_seniority_c_level, 0) AS SMALLINT) AS b2b_seniority_c_level,
    CAST(NULLIF(production_segments.b2b_seniority_director, 0) AS SMALLINT) AS b2b_seniority_director,
    CAST(NULLIF(production_segments.b2b_seniority_founder, 0) AS SMALLINT) AS b2b_seniority_founder,
    CAST(NULLIF(production_segments.b2b_seniority_manager, 0) AS SMALLINT) AS b2b_seniority_manager,
    CAST(NULLIF(production_segments.b2b_seniority_non_management, 0) AS SMALLINT) AS b2b_seniority_non_management,
    CAST(NULLIF(production_segments.b2b_seniority_owner_or_partner, 0) AS SMALLINT) AS b2b_seniority_owner_or_partner,
    CAST(NULLIF(production_segments.b2b_seniority_retired, 0) AS SMALLINT) AS b2b_seniority_retired,
    CAST(NULLIF(production_segments.b2b_seniority_staff, 0) AS SMALLINT) AS b2b_seniority_staff,
    CAST(NULLIF(production_segments.b2b_seniority_student, 0) AS SMALLINT) AS b2b_seniority_student,
    CAST(NULLIF(production_segments.b2b_seniority_vice_president, 0) AS SMALLINT) AS b2b_seniority_vice_president,
    CAST(NULLIF(production_segments.b2b_supply_chain_decision_makers, 0) AS SMALLINT) AS b2b_supply_chain_decision_makers,
    CAST(NULLIF(production_segments.b2b_supply_chain_executives, 0) AS SMALLINT) AS b2b_supply_chain_executives,
    CAST(NULLIF(production_segments.b2b_supply_chain_managers, 0) AS SMALLINT) AS b2b_supply_chain_managers,
    CAST(NULLIF(production_segments.b2b_technology_decision_makers, 0) AS SMALLINT) AS b2b_technology_decision_makers,
    CAST(NULLIF(production_segments.b2b_technology_executives, 0) AS SMALLINT) AS b2b_technology_executives,
    CAST(NULLIF(production_segments.b2b_technology_managers, 0) AS SMALLINT) AS b2b_technology_managers,
    CAST(NULLIF(production_segments.cat_social_media, 0) AS SMALLINT) AS cat_social_media,
    CAST(NULLIF(production_segments.demo_age_18_19, 0) AS SMALLINT) AS demo_age_18_19,
    CAST(NULLIF(production_segments.demo_age_20_24, 0) AS SMALLINT) AS demo_age_20_24,
    CAST(NULLIF(production_segments.demo_age_20_29, 0) AS SMALLINT) AS demo_age_20_29,
    CAST(NULLIF(production_segments.demo_age_25_29, 0) AS SMALLINT) AS demo_age_25_29,
    CAST(NULLIF(production_segments.demo_age_30_34, 0) AS SMALLINT) AS demo_age_30_34,
    CAST(NULLIF(production_segments.demo_age_30_39, 0) AS SMALLINT) AS demo_age_30_39,
    CAST(NULLIF(production_segments.demo_age_35_39, 0) AS SMALLINT) AS demo_age_35_39,
    CAST(NULLIF(production_segments.demo_age_40_44, 0) AS SMALLINT) AS demo_age_40_44,
    CAST(NULLIF(production_segments.demo_age_40_49, 0) AS SMALLINT) AS demo_age_40_49,
    CAST(NULLIF(production_segments.demo_age_45_49, 0) AS SMALLINT) AS demo_age_45_49,
    CAST(NULLIF(production_segments.demo_age_50_54, 0) AS SMALLINT) AS demo_age_50_54,
    CAST(NULLIF(production_segments.demo_age_50_59, 0) AS SMALLINT) AS demo_age_50_59,
    CAST(NULLIF(production_segments.demo_age_55_59, 0) AS SMALLINT) AS demo_age_55_59,
    CAST(NULLIF(production_segments.demo_age_60_64, 0) AS SMALLINT) AS demo_age_60_64,
    CAST(NULLIF(production_segments.demo_age_60_Older, 0) AS SMALLINT) AS demo_age_60_Older,
    CAST(NULLIF(production_segments.demo_age_65_69, 0) AS SMALLINT) AS demo_age_65_69,
    CAST(NULLIF(production_segments.demo_age_70_75, 0) AS SMALLINT) AS demo_age_70_75,
    CAST(NULLIF(production_segments.demo_age_70_Older, 0) AS SMALLINT) AS demo_age_70_Older,
    CAST(NULLIF(production_segments.demo_age_baby_boomers, 0) AS SMALLINT) AS demo_age_baby_boomers,
    CAST(NULLIF(production_segments.demo_age_elders, 0) AS SMALLINT) AS demo_age_elders,
    CAST(NULLIF(production_segments.demo_age_gen_x, 0) AS SMALLINT) AS demo_age_gen_x,
    CAST(NULLIF(production_segments.demo_age_gen_y, 0) AS SMALLINT) AS demo_age_gen_y,
    production_segments.demo_age_lifestages,
    production_segments.demo_education,
    CAST(NULLIF(production_segments.demo_education_college, 0) AS SMALLINT) AS demo_education_college,
    CAST(NULLIF(production_segments.demo_education_grad, 0) AS SMALLINT) AS demo_education_grad,
    CAST(NULLIF(production_segments.demo_education_high_school, 0) AS SMALLINT) AS demo_education_high_school,
    CAST(NULLIF(production_segments.demo_education_student, 0) AS SMALLINT) AS demo_education_student,
    CAST(NULLIF(production_segments.demo_education_undergrad, 0) AS SMALLINT) AS demo_education_undergrad,
    CAST(NULLIF(production_segments.demo_education_vocation, 0) AS SMALLINT) AS demo_education_vocation,
    CAST(NULLIF(production_segments.demo_emp_status_employed, 0) AS SMALLINT) AS demo_emp_status_employed,
    CAST(NULLIF(production_segments.demo_ethnicity_hispanic, 0) AS SMALLINT) AS demo_ethnicity_hispanic,
    production_segments.demo_gender,
    CAST(NULLIF(production_segments.demo_gender_female, 0) AS SMALLINT) AS demo_gender_female,
    CAST(NULLIF(production_segments.demo_gender_male, 0) AS SMALLINT) AS demo_gender_male,
    CAST(NULLIF(production_segments.demo_high_net_worth, 0) AS SMALLINT) AS demo_high_net_worth,
    CAST(NULLIF(production_segments.demo_lang_arabic, 0) AS SMALLINT) AS demo_lang_arabic,
    CAST(NULLIF(production_segments.demo_lang_chinese, 0) AS SMALLINT) AS demo_lang_chinese,
    CAST(NULLIF(production_segments.demo_lang_farsi, 0) AS SMALLINT) AS demo_lang_farsi,
    CAST(NULLIF(production_segments.demo_lang_french, 0) AS SMALLINT) AS demo_lang_french,
    CAST(NULLIF(production_segments.demo_lang_german, 0) AS SMALLINT) AS demo_lang_german,
    CAST(NULLIF(production_segments.demo_lang_group_indian, 0) AS SMALLINT) AS demo_lang_group_indian,
    CAST(NULLIF(production_segments.demo_lang_hindi, 0) AS SMALLINT) AS demo_lang_hindi,
    CAST(NULLIF(production_segments.demo_lang_italian, 0) AS SMALLINT) AS demo_lang_italian,
    CAST(NULLIF(production_segments.demo_lang_japanese, 0) AS SMALLINT) AS demo_lang_japanese,
    CAST(NULLIF(production_segments.demo_lang_korean, 0) AS SMALLINT) AS demo_lang_korean,
    CAST(NULLIF(production_segments.demo_lang_portuguese, 0) AS SMALLINT) AS demo_lang_portuguese,
    CAST(NULLIF(production_segments.demo_lang_russian, 0) AS SMALLINT) AS demo_lang_russian,
    CAST(NULLIF(production_segments.demo_lang_spanish, 0) AS SMALLINT) AS demo_lang_spanish,
    CAST(NULLIF(production_segments.demo_lang_urdu, 0) AS SMALLINT) AS demo_lang_urdu,
    CAST(NULLIF(production_segments.int_inter_online_act, 0) AS SMALLINT) AS int_inter_online_act,
    production_segments.company_normalized_industry,
    CAST(NULLIF(production_mfg_segments.b2b_diversity_business_type, 0) AS SMALLINT) AS b2b_diversity_business_type,
    CAST(NULLIF(production_mfg_segments.b2b_us_federal_gov_approved_supplier, 0) AS SMALLINT) AS b2b_us_federal_gov_approved_supplier,
    CAST(NULLIF(production_mfg_segments.mfg_business_services, 0) AS SMALLINT) AS mfg_business_services,
    CAST(NULLIF(production_mfg_segments.mfg_business_services_custom_services, 0) AS SMALLINT) AS mfg_business_services_custom_services,
    CAST(NULLIF(production_mfg_segments.mfg_business_type_contract_manufacturer, 0) AS SMALLINT) AS mfg_business_type_contract_manufacturer,
    CAST(NULLIF(production_mfg_segments.mfg_business_type_distributor, 0) AS SMALLINT) AS mfg_business_type_distributor,
    CAST(NULLIF(production_mfg_segments.mfg_business_type_manufacturer, 0) AS SMALLINT) AS mfg_business_type_manufacturer,
    CAST(NULLIF(production_mfg_segments.mfg_business_type_supplier, 0) AS SMALLINT) AS mfg_business_type_supplier,
    CAST(NULLIF(production_mfg_segments.mfg_certifications_as_9100, 0) AS SMALLINT) AS mfg_certifications_as_9100,
    CAST(NULLIF(production_mfg_segments.mfg_certifications_fda, 0) AS SMALLINT) AS mfg_certifications_fda,
    CAST(NULLIF(production_mfg_segments.mfg_certifications_iso, 0) AS SMALLINT) AS mfg_certifications_iso,
    CAST(NULLIF(production_mfg_segments.mfg_certifications_iso9001, 0) AS SMALLINT) AS mfg_certifications_iso9001,
    CAST(NULLIF(production_mfg_segments.mfg_certifications_itar, 0) AS SMALLINT) AS mfg_certifications_itar,
    CAST(NULLIF(production_mfg_segments.mfg_certifications_lean_manufacturer, 0) AS SMALLINT) AS mfg_certifications_lean_manufacturer,
    CAST(NULLIF(production_mfg_segments.mfg_certifications_leed, 0) AS SMALLINT) AS mfg_certifications_leed,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products, 0) AS SMALLINT) AS mfg_consumer_products,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_animal_and_pet_products, 0) AS SMALLINT) AS mfg_consumer_products_animal_and_pet_products,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_apparel_and_textiles, 0) AS SMALLINT) AS mfg_consumer_products_apparel_and_textiles,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_appliances, 0) AS SMALLINT) AS mfg_consumer_products_appliances,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_child_and_baby_care_products, 0) AS SMALLINT) AS mfg_consumer_products_child_and_baby_care_products,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_computers_av_and_peripherals, 0) AS SMALLINT) AS mfg_consumer_products_computers_av_and_peripherals,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_consumer_medical_products, 0) AS SMALLINT) AS mfg_consumer_products_consumer_medical_products,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_consumer_vehicles_and_components, 0) AS SMALLINT) AS mfg_consumer_products_consumer_vehicles_and_components,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_cosmetics, 0) AS SMALLINT) AS mfg_consumer_products_cosmetics,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_food_and_food_products, 0) AS SMALLINT) AS mfg_consumer_products_food_and_food_products,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_household_products, 0) AS SMALLINT) AS mfg_consumer_products_household_products,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_jewelry, 0) AS SMALLINT) AS mfg_consumer_products_jewelry,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_marine_products, 0) AS SMALLINT) AS mfg_consumer_products_marine_products,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_photography, 0) AS SMALLINT) AS mfg_consumer_products_photography,
    CAST(NULLIF(production_mfg_segments.mfg_consumer_products_recreation_and_sports_equipment, 0) AS SMALLINT) AS mfg_consumer_products_recreation_and_sports_equipment,
    CAST(NULLIF(production_mfg_segments.mfg_defense_and_law_enforcement_aerospace_aircraft, 0) AS SMALLINT) AS mfg_defense_and_law_enforcement_aerospace_aircraft,
    CAST(NULLIF(production_mfg_segments.mfg_defense_and_law_enforcement_equipment_and_supplies, 0) AS SMALLINT) AS mfg_defense_and_law_enforcement_equipment_and_supplies,
    CAST(NULLIF(production_mfg_segments.mfg_defense_and_law_enforcement_guns_ammunition, 0) AS SMALLINT) AS mfg_defense_and_law_enforcement_guns_ammunition,
    CAST(NULLIF(production_mfg_segments.mfg_defense_and_law_enforcement_manufacturing, 0) AS SMALLINT) AS mfg_defense_and_law_enforcement_manufacturing,
    CAST(NULLIF(production_mfg_segments.mfg_defense_and_law_enforcement_military_equipment, 0) AS SMALLINT) AS mfg_defense_and_law_enforcement_military_equipment,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing, 0) AS SMALLINT) AS mfg_general_manufacturing,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing_automation_systems_and_components, 0) AS SMALLINT) AS mfg_general_manufacturing_automation_systems_and_components,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing_electrical_and_electronic_components, 0) AS SMALLINT) AS mfg_general_manufacturing_electrical_and_electronic_components,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing_facility_equipment_and_supplies, 0) AS SMALLINT) AS mfg_general_manufacturing_facility_equipment_and_supplies,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing_fluid_control_and_components, 0) AS SMALLINT) AS mfg_general_manufacturing_fluid_control_and_components,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing_hardware_and_fasteners, 0) AS SMALLINT) AS mfg_general_manufacturing_hardware_and_fasteners,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing_machinery_tools_and_supplies, 0) AS SMALLINT) AS mfg_general_manufacturing_machinery_tools_and_supplies,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing_manufacturing_equipment, 0) AS SMALLINT) AS mfg_general_manufacturing_manufacturing_equipment,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing_packaging_and_materials_handling, 0) AS SMALLINT) AS mfg_general_manufacturing_packaging_and_materials_handling,
    CAST(NULLIF(production_mfg_segments.mfg_general_manufacturing_test_measurement_and_positioning, 0) AS SMALLINT) AS mfg_general_manufacturing_test_measurement_and_positioning,
    CAST(NULLIF(production_mfg_segments.mfg_industries_aerospace, 0) AS SMALLINT) AS mfg_industries_aerospace,
    CAST(NULLIF(production_mfg_segments.mfg_industries_automotive, 0) AS SMALLINT) AS mfg_industries_automotive,
    CAST(NULLIF(production_mfg_segments.mfg_industries_biomedical, 0) AS SMALLINT) AS mfg_industries_biomedical,
    CAST(NULLIF(production_mfg_segments.mfg_industries_construction, 0) AS SMALLINT) AS mfg_industries_construction,
    CAST(NULLIF(production_mfg_segments.mfg_industries_defense, 0) AS SMALLINT) AS mfg_industries_defense,
    CAST(NULLIF(production_mfg_segments.mfg_industries_electronics, 0) AS SMALLINT) AS mfg_industries_electronics,
    CAST(NULLIF(production_mfg_segments.mfg_industries_environmental, 0) AS SMALLINT) AS mfg_industries_environmental,
    CAST(NULLIF(production_mfg_segments.mfg_industries_healthcare, 0) AS SMALLINT) AS mfg_industries_healthcare,
    CAST(NULLIF(production_mfg_segments.mfg_industries_pharmaceutical, 0) AS SMALLINT) AS mfg_industries_pharmaceutical,
    CAST(NULLIF(production_mfg_segments.mfg_industries_renewable_energy, 0) AS SMALLINT) AS mfg_industries_renewable_energy,
    CAST(NULLIF(production_mfg_segments.mfg_industries_transportation, 0) AS SMALLINT) AS mfg_industries_transportation,
    CAST(NULLIF(production_mfg_segments.mfg_machinery, 0) AS SMALLINT) AS mfg_machinery,
    CAST(NULLIF(production_mfg_segments.mfg_machinery_cnc, 0) AS SMALLINT) AS mfg_machinery_cnc,
    CAST(NULLIF(production_mfg_segments.mfg_machinery_presses, 0) AS SMALLINT) AS mfg_machinery_presses,
    CAST(NULLIF(production_mfg_segments.mfg_machinery_printing, 0) AS SMALLINT) AS mfg_machinery_printing,
    CAST(NULLIF(production_mfg_segments.mfg_materials_and_chemicals, 0) AS SMALLINT) AS mfg_materials_and_chemicals,
    CAST(NULLIF(production_mfg_segments.mfg_materials_and_chemicals_adhesives_tapes_and_sealants, 0) AS SMALLINT) AS mfg_materials_and_chemicals_adhesives_tapes_and_sealants,
    CAST(NULLIF(production_mfg_segments.mfg_materials_and_chemicals_chemicals_and_chemical_products, 0) AS SMALLINT) AS mfg_materials_and_chemicals_chemicals_and_chemical_products,
    CAST(NULLIF(production_mfg_segments.mfg_materials_and_chemicals_metals_and_metal_products, 0) AS SMALLINT) AS mfg_materials_and_chemicals_metals_and_metal_products,
    CAST(NULLIF(production_mfg_segments.mfg_materials_and_chemicals_polymers_and_polymer_products, 0) AS SMALLINT) AS mfg_materials_and_chemicals_polymers_and_polymer_products,
    CAST(NULLIF(production_tech_install_segments.tech_inst_cloud_services, 0) AS SMALLINT) AS tech_inst_cloud_services,
    CAST(NULLIF(production_tech_install_segments.tech_inst_cloud_services_cloud_infrastructure_computing, 0) AS SMALLINT) AS tech_inst_cloud_services_cloud_infrastructure_computing,
    CAST(NULLIF(production_tech_install_segments.tech_inst_cloud_services_platform_as_a_service, 0) AS SMALLINT) AS tech_inst_cloud_services_platform_as_a_service,
    CAST(NULLIF(production_tech_install_segments.tech_inst_communications_tech_email, 0) AS SMALLINT) AS tech_inst_communications_tech_email,
    CAST(NULLIF(production_tech_install_segments.tech_inst_communications_technologies, 0) AS SMALLINT) AS tech_inst_communications_technologies,
    CAST(NULLIF(production_tech_install_segments.tech_inst_customer_mgmt, 0) AS SMALLINT) AS tech_inst_customer_mgmt,
    CAST(NULLIF(production_tech_install_segments.tech_inst_customer_mgmt_help_desk, 0) AS SMALLINT) AS tech_inst_customer_mgmt_help_desk,
    CAST(NULLIF(production_tech_install_segments.tech_inst_data_center, 0) AS SMALLINT) AS tech_inst_data_center,
    CAST(NULLIF(production_tech_install_segments.tech_inst_data_center_operating_systems_and_computing_languages, 0) AS SMALLINT) AS tech_inst_data_center_operating_systems_and_computing_languages,
    CAST(NULLIF(production_tech_install_segments.tech_inst_data_center_system_analytics_and_monitoring, 0) AS SMALLINT) AS tech_inst_data_center_system_analytics_and_monitoring,
    CAST(NULLIF(production_tech_install_segments.tech_inst_enterprise_apps, 0) AS SMALLINT) AS tech_inst_enterprise_apps,
    CAST(NULLIF(production_tech_install_segments.tech_inst_enterprise_apps_commerce, 0) AS SMALLINT) AS tech_inst_enterprise_apps_commerce,
    CAST(NULLIF(production_tech_install_segments.tech_inst_enterprise_apps_hr_mgmt_systems, 0) AS SMALLINT) AS tech_inst_enterprise_apps_hr_mgmt_systems,
    CAST(NULLIF(production_tech_install_segments.tech_inst_enterprise_content, 0) AS SMALLINT) AS tech_inst_enterprise_content,
    CAST(NULLIF(production_tech_install_segments.tech_inst_enterprise_content_document_mgmt, 0) AS SMALLINT) AS tech_inst_enterprise_content_document_mgmt,
    CAST(NULLIF(production_tech_install_segments.tech_inst_hardware, 0) AS SMALLINT) AS tech_inst_hardware,
    CAST(NULLIF(production_tech_install_segments.tech_inst_hardware_consumer_electronics_computers_and_software, 0) AS SMALLINT) AS tech_inst_hardware_consumer_electronics_computers_and_software,
    CAST(NULLIF(production_tech_install_segments.tech_inst_it_governance, 0) AS SMALLINT) AS tech_inst_it_governance,
    CAST(NULLIF(production_tech_install_segments.tech_inst_it_governance_application_development_and_mgmt, 0) AS SMALLINT) AS tech_inst_it_governance_application_development_and_mgmt,
    CAST(NULLIF(production_tech_install_segments.tech_inst_it_governance_change_mgmt, 0) AS SMALLINT) AS tech_inst_it_governance_change_mgmt,
    CAST(NULLIF(production_tech_install_segments.tech_inst_it_governance_software_configuration_mgmt, 0) AS SMALLINT) AS tech_inst_it_governance_software_configuration_mgmt,
    CAST(NULLIF(production_tech_install_segments.tech_inst_marketing_performance_mgmt, 0) AS SMALLINT) AS tech_inst_marketing_performance_mgmt,
    CAST(NULLIF(production_tech_install_segments.tech_inst_marketing_performance_mgmt_business_intelligence, 0) AS SMALLINT) AS tech_inst_marketing_performance_mgmt_business_intelligence,
    CAST(NULLIF(production_tech_install_segments.tech_inst_marketing_performance_mgmt_measurement, 0) AS SMALLINT) AS tech_inst_marketing_performance_mgmt_measurement,
    CAST(NULLIF(production_tech_install_segments.tech_inst_network_computing, 0) AS SMALLINT) AS tech_inst_network_computing,
    CAST(NULLIF(production_tech_install_segments.tech_inst_network_computing_network_mgmt_hardware, 0) AS SMALLINT) AS tech_inst_network_computing_network_mgmt_hardware,
    CAST(NULLIF(production_tech_install_segments.tech_inst_network_computing_network_mgmt_software, 0) AS SMALLINT) AS tech_inst_network_computing_network_mgmt_software,
    CAST(NULLIF(production_tech_install_segments.tech_inst_productivity_solutions, 0) AS SMALLINT) AS tech_inst_productivity_solutions,
    CAST(NULLIF(production_tech_install_segments.tech_inst_productivity_solutions_collaboration, 0) AS SMALLINT) AS tech_inst_productivity_solutions_collaboration,
    CAST(NULLIF(production_tech_install_segments.tech_inst_software, 0) AS SMALLINT) AS tech_inst_software,
    CAST(NULLIF(production_tech_install_segments.tech_inst_software_search_engine, 0) AS SMALLINT) AS tech_inst_software_search_engine,
    CAST(NULLIF(production_tech_install_segments.tech_inst_software_server_technologies, 0) AS SMALLINT) AS tech_inst_software_server_technologies,
    CAST(NULLIF(production_tech_install_segments.tech_inst_vertical_markets, 0) AS SMALLINT) AS tech_inst_vertical_markets,
    CAST(NULLIF(production_tech_install_segments.tech_inst_vertical_markets_academic_and_education_mgmt_software, 0) AS SMALLINT) AS tech_inst_vertical_markets_academic_and_education_mgmt_software,
    CAST(NULLIF(production_tech_install_segments.tech_inst_web_oriented_arch_online_video_platform, 0) AS SMALLINT) AS tech_inst_web_oriented_arch_online_video_platform,
    CAST(NULLIF(production_tech_install_segments.tech_inst_web_oriented_arch_remote_server_solutions, 0) AS SMALLINT) AS tech_inst_web_oriented_arch_remote_server_solutions,
    CAST(NULLIF(production_tech_install_segments.tech_inst_web_oriented_arch_social_media_systems, 0) AS SMALLINT) AS tech_inst_web_oriented_arch_social_media_systems,
    CAST(NULLIF(production_tech_install_segments.tech_inst_web_oriented_arch_virtualization_data_center, 0) AS SMALLINT) AS tech_inst_web_oriented_arch_virtualization_data_center,
    CAST(NULLIF(production_tech_install_segments.tech_inst_web_oriented_arch_virtualization_platform_mgmt, 0) AS SMALLINT) AS tech_inst_web_oriented_arch_virtualization_platform_mgmt,
    CAST(NULLIF(production_tech_install_segments.tech_inst_web_oriented_arch_web_and_portal_technology, 0) AS SMALLINT) AS tech_inst_web_oriented_arch_web_and_portal_technology,
    CAST(NULLIF(production_tech_install_segments.tech_inst_web_oriented_arch_web_content_mgmt_system, 0) AS SMALLINT) AS tech_inst_web_oriented_arch_web_content_mgmt_system,
    CAST(NULLIF(production_tech_install_segments.tech_inst_web_oriented_architecture, 0) AS SMALLINT) AS tech_inst_web_oriented_architecture,
    production_persons.random_tenth_percent
FROM production_persons
LEFT OUTER JOIN export.athena_b2b_emails ON production_persons.id = export.athena_b2b_emails.person_id
LEFT OUTER JOIN export.athena_personal_emails_raw ON production_persons.id = export.athena_personal_emails_raw.person_id
LEFT OUTER JOIN export.athena_personal_emails_md5 ON production_persons.id = export.athena_personal_emails_md5.person_id
LEFT OUTER JOIN export.athena_emails_onboarding ON production_persons.id = export.athena_emails_onboarding.person_id
LEFT OUTER JOIN production_companies ON production_persons.matched_processed_company_id = production_companies.id
LEFT OUTER JOIN production_segments ON production_persons.id = production_segments.person_id
LEFT OUTER JOIN production_mfg_segments ON production_companies.domain = production_mfg_segments.domain
LEFT OUTER JOIN production_tech_install_segments ON production_companies.domain = production_tech_install_segments.domain